name: my_app
description: "A new Flutter accounting app."
publish_to: 'none'
version: 2.2.3+223

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  sqflite: ^2.3.0
  path: ^1.8.3
  csv: ^5.0.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.3.2
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

dependency_overrides:
  path_provider_foundation: 2.3.2
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

